# permissions for end users to edit wordpresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: wordpress-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: meduim
    app.kubernetes.io/part-of: meduim
    app.kubernetes.io/managed-by: kustomize
  name: wordpress-editor-role
rules:
- apiGroups:
  - medium.example.org
  resources:
  - wordpresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - medium.example.org
  resources:
  - wordpresses/status
  verbs:
  - get
